### PR TITLE
MM-56540 - Support for live captions

### PR DESCRIPTION
**Pull request by cpoile**
#### Summary
- Just a placeholder PR, will update with merged transcriber commit/version once that's all through. 
- Need to update transcriber or else the transcriber config values won't be passed to the transcriber container.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-56540

### CODE REVIEW

**Comment by cpoile** [comment]
@streamer45 Confirmed that plugin v0.24.0 works with this newer version of the offloader.

**Comment by streamer45** [comment]
@cpoile Something I've noticed that may need review. This code isn't playing well with the `-dev` suffix it seems:

https://github.com/mattermost/calls-offloader/blob/4413f3bd70917fa8ed3833286ddfe5dcbd768216/service/docker/utils.go#L31-L32

**Comment by cpoile** [comment]
@streamer45 Fixed -- I chose to keep it constrained to `-dev#`, but if you want we can allow anything, in order to prevent that from happening in the future? (basically take away that last commit and instead remove the `$`)

**Review by streamer45 — APPROVED** [review]
Looks good!

**Pull request merged**
